### ISSUE TITLE
Ansibilize Avalon Fedora Server

### ISSUE THREAD

**Issue by cachemeoutside** [UCLALibrary/avalon#19]
**Tasks**
- [x] Create MySQL user for Fedora Modeshape backend
- [x] Create CName for avalonfedora.library.ucla.edu to point to p-w-avalonfedora01
- [x] Deploy Fedora server with Ansible playbook

**Acceptance Criteria**
- [x] http://avalonfedora.library.ucla.edu/fcrepo should point to Fedora

**Comment by cachemeoutside** [comment]
Ansible roles used described in playbook here: https://github.com/UCLALibrary/ansible_uclalib_plays/blob/master/avalon/lib_fedora.yml

Fedora variables stored locally on host vars
